### ISSUE TITLE
Error in load_word_embeddings()

### ISSUE THREAD

**Issue by Masum06** [Hironsan/anago#15]
Hi @Hironsan, 
Thanks for making Anago. I have an error, I would be glad if you look into.
While executing the line 
`embeddings = load_word_embeddings(p.vocab_word, embedding_path, model_config.word_embedding_size)`
I am getting this error in line 83 of reader.py. Surprisingly, even if I put some newline and rearrange the lines, the error still stays in line 83!
I have tried changing the encoding to 'utf-8' or 'Latin-1' with the following change in line 82 in 'reader.py', but nothing worked
`    with open(glove_filename, encoding='utf-8') as f:`
```
Traceback (most recent call last):
  File "<pyshell#17>", line 1, in <module>
    embeddings = load_word_embeddings(p.vocab_word, embedding_path, model_config.word_embedding_size)
  File "G:/Others/Thesis/anago\anago\data\reader.py", line 83, in load_word_embeddings
    line = line.strip().split(' ')
  File "C:\Users\MasumPC\AppData\Local\Programs\Python\Python35\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 2776: character maps to <undefined>
```

**Comment by Masum06** [comment]
@Hironsan, Line 34 and 35 is supposed to be commented, but they are not. This was causing the error. Removing it worked fine. Please fix it.
`        >>> filename = 'conll2003/en/ner/train.txt'
        >>> data, labels = load_data_and_labels(filename)`

**Comment by Hironsan** [comment]
@Masum06 Thanks! I will check it.
