### ISSUE TITLE
Useless F1 score code

### ISSUE THREAD

**Issue by grafael** [Hironsan/anago#19]
Seems that this function is not being used anywhere.
https://github.com/Hironsan/anago/blob/c1e66ecc0f327b85b1e2707a845664e22a164813/anago/metrics.py#L78

Despite the F1 score, instead create your own function, you could use the scikit-learn: http://scikit-learn.org/stable/modules/generated/sklearn.metrics.f1_score.html

**Comment by Hironsan** [comment]
scikit-learn's f1_score function is not suitable for sequence labeling.

We could use seqeval:
* https://github.com/chakki-works/seqeval
