### ISSUE TITLE
cannot evaluate the model

### ISSUE THREAD

**Issue by yulirain** [Hironsan/anago#2]
Hi, @Hironsan , I have successfully trained the model, but when I evaluate the model and test the model, It failed. The error is :

TypeError: Failed to convert object of type <type 'tuple'> to Tensor. Contents: (None, 100). Consider casting elements to a supported type.

Can you help me ? Thank you very much !

**Comment by Hironsan** [comment]
Hi, @yulirain, Thank you to let me know the error.

By the way, could you tell me what file and line the error occurred?
Is Keras's backend Tensorflow or Theano?

The information help me to solve the problem.

**Comment by yulirain** [comment]
Hi, Hiroki,

	Thanks very much for your reply.

        It is my fault. I directly carried out the function “anago.Evaluator()” without loading the embedding vector.

	Now, I can successfully evaluate the trained model, and it works normally, F1=91.03  for the sample data.

	However, I meet another question. The F1 is only 26 for NER by using the corpus created by myself, the performance can not reach your level.

	Can you tell me some suggestion when using your model ?

	Thank you very much again!

Sincerely yours,


Li YU   

National Science Library, Chinese Academy of Sciences
No.33, Zhong Guan Cun West Road
Beijing China, 100190
