### ISSUE TITLE
F1 score of 0 for character level sequence labelling task 

### ISSUE THREAD

**Issue by Timilehin** [Hironsan/anago#20]
Training data looks like:
<img width="321" alt="tra" src="https://user-images.githubusercontent.com/3932372/34647231-b399cc1e-f331-11e7-92dd-47ecc01c3750.png">

and training results look like:
<img width="578" alt="cmd" src="https://user-images.githubusercontent.com/3932372/34647237-c32b6336-f331-11e7-986d-8fe740a9c87a.png">

Also worth adding that whenever I add a new period at the end of each character sequence, it never begins training and stops at `Epoch 1/15` with no progress bar. I'll be happy to share training data with you if that will help reproduce the issue.

**Comment by riteshpanjwani** [comment]
Hi,

I am facing the same issue for POS tag data.

**Comment by tc64** [comment]
I think you cannot just use any tag label schema and expect evaluation function to work correctly, without editing anago.metrics.get_entities - it expects BILO.

**Comment by Timilehin** [comment]
Thanks @tc64 
@riteshpanjwani one workaround  that made it work for me wass to add B- to the beginning of every label.

**Comment by Hironsan** [comment]
Not use BILO. Use IOB2.

Because anago ver0.0.5 assumes that training data is labeled by IOB2.

I will fix the problem in ver 1.0.0.
