### ISSUE TITLE
Can you provide the Japanese training example? 

### ISSUE THREAD

**Issue by jlsche** [Hironsan/anago#21]
Hi, 
I'm wondering what does the Japanese training data look like.
Are they segmented by word or by character?
also the data for training word2vec, 
are they segmented in the same way?

**Comment by Hironsan** [comment]
In the same way of English dataset, Japanese training data are also segmented by word.
* https://github.com/Hironsan/anago/tree/master/data/conll2003/en/ner

I used pre-trained word embeddings.
* https://qiita.com/Hironsan/items/513b9f93752ecee9e670
