### ISSUE TITLE
AttributeError: 'ChainCRF' object has no attribute 'inbound_nodes

### ISSUE THREAD

**Issue by Xnsam** [Hironsan/anago#28]
hi,

when i run model.train i get the following error...

`---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-29-a07511cbedf1> in <module>()
----> 1 model.train(x_train, y_train, x_val, y_val)

~/anaconda3/envs/py3/lib/python3.6/site-packages/anago/wrapper.py in train(self, x_train, y_train, x_valid, y_valid, vocab_init)
     48                           checkpoint_path=self.log_dir,
     49                           preprocessor=self.p)
---> 50         trainer.train(x_train, y_train, x_valid, y_valid)
     51 
     52     def eval(self, x_test, y_test):

~/anaconda3/envs/py3/lib/python3.6/site-packages/anago/trainer.py in train(self, x_train, y_train, x_valid, y_valid)
     36 
     37         self.model.compile(loss=self.model.crf.loss,
---> 38                            optimizer=Adam(lr=self.training_config.learning_rate),
     39                            )
     40 

~/anaconda3/envs/py3/lib/python3.6/site-packages/keras/engine/training.py in compile(self, optimizer, loss, metrics, loss_weights, sample_weight_mode, weighted_metrics, target_tensors, **kwargs)
    825                 with K.name_scope(self.output_names[i] + '_loss'):
    826                     output_loss = weighted_loss(y_true, y_pred,
--> 827                                                 sample_weight, mask)
    828                 if len(self.outputs) > 1:
    829                     self.metrics_tensors.append(output_loss)

~/anaconda3/envs/py3/lib/python3.6/site-packages/keras/engine/training.py in weighted(y_true, y_pred, weights, mask)
    424         """
    425         # score_array has ndim >= 2
--> 426         score_array = fn(y_true, y_pred)
    427         if mask is not None:
    428             # Cast the mask to floatX to avoid float64 upcasting in theano

~/anaconda3/envs/py3/lib/python3.6/site-packages/anago/layers.py in loss(self, y_true, y_pred)
    319         """Linear Chain Conditional Random Field loss function.
    320         """
--> 321         mask = self._fetch_mask()
    322         return chain_crf_loss(y_true, y_pred, self.U, self.b_start, self.b_end, mask)
    323 

~/anaconda3/envs/py3/lib/python3.6/site-packages/anago/layers.py in _fetch_mask(self)
    274     def _fetch_mask(self):
    275         mask = None
--> 276         if self.inbound_nodes:
    277             mask = self.inbound_nodes[0].input_masks[0]
    278         return mask

AttributeError: 'ChainCRF' object has no attribute 'inbound_nodes'`

It would be really great if you could suggest a work around for this...

Thank you..

**Comment by Hironsan** [comment]
Hi @Xnsam 

This problem is solved by https://github.com/Hironsan/anago/pull/26.

But I didn't update package. So this error happened.

I will update it as soon as possible. Wait a moment!

**Comment by Hironsan** [comment]
I released [anaGo 0.0.5](https://github.com/Hironsan/anago/releases/tag/0.0.5).

Please use version 0.0.5 instead of older versions.
