### ISSUE TITLE
GPU

### ISSUE THREAD

**Issue by jodevak** [Hironsan/anago#29]
I ran a test across a GPU based instance, but i didnt see any speed improvments. Is there something that i would need to modify in order to support GPU ? thanks

**Comment by ismaeIfm** [comment]
do you have tensorflow-gpu installed?

**Comment by jodevak** [comment]
Yes, its an aws instance.

**Comment by ismaeIfm** [comment]
In order to help you, you need to give more feedback. I would suggest to check that Keras is using tensorflow as backend, that tensorflow-gpu is installed and that cuda and cudnn are properly installed.
