### ISSUE TITLE
Accuracy during epochs

### ISSUE THREAD

**Issue by jodevak** [Hironsan/anago#35]
Is there a way to print the accuracy during training epochs (not when an epoch is finished) ? i tried setting metrics=['sparse_categorical_accuracy'] inside trainer.py. But its giving me this message !

> AttributeError: 'ChainCRF' object has no attribute 'accuracy'

**Comment by sehoi** [comment]
anago/metric.py get_callbacks() function only calculates the f1-score of validation set.
you need to modify callback function.

**Comment by dterg** [comment]
For some reason I do no get the F-score for the validation set during training as shown in the readme screenshots, only the loss. The F1 on the validation is only shown once and epoch finishes. Any ideas? The ```get_callbacks``` function does have the valid_steps and valid_batches inputted as arguments - not sure why this is not shown.

**Comment by sehoi** [comment]
@dterg that's no problem that the F1 on the validation is only shown once an epoch finishes.
because verification is not performed until one epoch is over.

**Comment by dterg** [comment]
I must have misread the readme due to the misaligned F1 values which seem to be before epoch ends.
![image](https://user-images.githubusercontent.com/18417945/37690075-b5ab99ee-2ca0-11e8-9099-e6922a1a575e.png)
