### ISSUE TITLE
KeyError: 'I-PRT'

### ISSUE THREAD

**Issue by MesiA** [Hironsan/anago#37]
While using Conll2003/en/ner data for training.

KeyError: 'I-PRT'

**Comment by Hironsan** [comment]
Hi @MesiA 
Thanks for valuable information.

Please show me stacktrace.

**Comment by Low-profile** [comment]
I met the same problem, it seems like the problem occurs due to 'I-PRT' tag didn't exist in the training set of conll03 chunking but in the valid set. There is a bug in handling unseen label in the evaluation process.
