### ISSUE TITLE
Calling Callbacks on training

### ISSUE THREAD

**Issue by dterg** [Hironsan/anago#39]
How are the callbacks (or the ``` get_callbacks ``` function) used? In keras thee ``` train ``` method takes callbacks as an argument but this doesn't seem to be the case here. Is it possible to use custom callback functions originally used with keras here? When extending the callbacks list with my custom callback, this gives an error that it's not iterable. I presume this is because the ``` fit_generator() ``` is used rather than the ``` fit() ``` method?

**Comment by Hironsan** [comment]
In anago 1.0.0, this problem is solved.
Thanks!


Example:

```python
file_name = '_'.join(['model_weights', '{epoch:02d}', '{f1:2.4f}']) + '.h5'
callback = ModelCheckpoint(os.path.join('logs', file_name),
                           monitor='f1',
                           save_weights_only=True)
model = anago.Sequence()
model.fit(x_train, y_train, x_test, y_test, callbacks=[callback])
```
