### ISSUE TITLE
pre-trained model of Named Entity Recognition in Japanese

### ISSUE THREAD

**Issue by Kensuke-Mitsuzawa** [Hironsan/anago#42]
You're showing an example of Japanese language in Readme.
Are you planning to put the pre-trained model in Japanese language also?

**Comment by Hironsan** [comment]
Probably "YES". In the future...

**Comment by duhaime** [comment]
@Hironsan do you have a pretrained model in Japanese that you would be willing to share with others? I'm working with a student who would benefit from such a model if you could share it!
