### ISSUE TITLE
custom optimizer is not used in trainer.py

### ISSUE THREAD

**Issue by ismaeIfm** [Hironsan/anago#45]
If you define a custom optimizer in a training_config to use it with the Trainer class, the optimizer is never used since  Adam is hardcoded as an optimizer. https://github.com/Hironsan/anago/blob/master/anago/trainer.py#L38

**Comment by ismaeIfm** [comment]
Same issue with  lr_decay and clip_gradients. I would suggest using only optimizer as parameter the same way keras handles it

**Comment by Hironsan** [comment]
In anaGo 1.0.0, this problem is solved.
Thanks!

Example:

```python
model = anago.Sequence(optimizer='rmsprop')
model.fit(x_train, y_train)
```
