### ISSUE TITLE
problem with word embedding?

### ISSUE THREAD

**Issue by trangtv57** [Hironsan/anago#53]
I have a problem with train dataset is small, so i think the number word in train dataset can't cover all word in test dataset, its mean some word in test dataset may  be not in set word of train. I don't know anago cover this problem or not. If yes, can you explain for me how you solve this problem. 
Thanks you

**Comment by Hironsan** [comment]
anago can handle with this problem.

Pass words set to WordPreprocessor. it expands vocabulary:

```python
vocab_init = {'word_1', 'word_2', ...}
p = WordPreprocessor(vocab_init=vocab_init)
p.fit(X, y)
```
