### ISSUE TITLE
Can we make use of POS tag as well from the RAW data for training?

### ISSUE THREAD

**Issue by psriram93** [Hironsan/anago#54]
I have observed that each line in the train set can take only the word and it's Named Entity tag. Can we pass the POS tag as well for training to obtain better results? As well as doing some feature engineering adding more columns useful for training.

**Comment by Hironsan** [comment]
Default model doesn't support any feature engineering.

But if you make your own model and preprocessor based on default model and preprocessor, you can use POS tag.
