### ISSUE TITLE
Save Trained Model.

### ISSUE THREAD

**Issue by xain123** [Hironsan/anago#63]
I have trained the model on my data set according to the instructions.  But i didn't find any way to save the trained model. Is there any way?

**Comment by nkansal96** [comment]
This is what I'm using to save the model:

```python
model = anago.Sequence()
model.train(X, y, x_test, y_test)
model.save(args.model_dir)
```

**Comment by xain123** [comment]
![image](https://user-images.githubusercontent.com/32290104/40394008-16ea77f4-5e3b-11e8-9d41-e721a34ab2df.png)
i an facing this issue while traning

**Comment by nkansal96** [comment]
I think this happens if your dataset is too small. There is another issue open for this.
