### ISSUE TITLE
No module named 'seqeval.metrics'

### ISSUE THREAD

**Issue by azuretime** [Hironsan/anago#68]
Hi

Thanks for sharing a great project. I faced an error which seems to be caused by an extra layer of 'seqeval' folder. Could you look into this issue?

Thank you!

------------------------

### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Google Colab
- **Python version**: 3

### Describe the problem
When I run 
`cd anago/`
`from anago.utils import load_data_and_labels`

I get
````
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-25-9b9f11ce63de> in <module>()
----> 1 from anago.utils import load_data_and_labels

/content/anago/anago/__init__.py in <module>()
----> 1 from anago.tagger import Tagger
      2 from anago.trainer import Trainer
      3 from anago.wrapper import Sequence

/content/anago/anago/tagger.py in <module>()
      3 """
      4 import numpy as np
----> 5 from seqeval.metrics.sequence_labeling import get_entities
      6 
      7 

ModuleNotFoundError: No module named 'seqeval.metrics'
````

**Comment by Hironsan** [comment]
Hello @azuretime !

I think you clone the repository.
In the case, you have to install `seqeval` package.

```bash
$ pip install seqeval
```

I will add seqeval to requirements.txt.
Thank you for sharing the problem!
