### ISSUE TITLE
Which paper is this repo corresponding to ?

### ISSUE THREAD

**Issue by reid3290** [Hironsan/anago#7]
Is this repo the implementation of [Bidirectional LSTM-CRF Models for Sequence Tagging](https://arxiv.org/abs/1508.01991)?

**Comment by Hironsan** [comment]
Hi @reid3290 

This library is based on the following paper:

* [Neural Architectures for Named Entity Recognition](https://arxiv.org/abs/1603.01360)

The paper you cited is very similar to the above one but some details are different.

**Comment by reid3290** [comment]
Thank you!
