### ISSUE TITLE
Download of test modell not working - Access Denied

### ISSUE THREAD

**Issue by jischebeck** [Hironsan/anago#71]
Hi Hiroki,
when downloading the modell, I get the following error.
Jan

```
<Code>AccessDenied</Code>
<Message>Access denied.</Message>
<Details>
Anonymous caller does not have storage.objects.get access to chakki/datasets/public/ner/models_en.zip.
</Details>
</Error>
```

**Comment by Hironsan** [comment]
In anago ver 1.0.7, you can download the model from the following link:

* [https://storage.googleapis.com/chakki/datasets/public/ner/conll2003_en.zip](https://storage.googleapis.com/chakki/datasets/public/ner/conll2003_en.zip)

Thanks
