### ISSUE TITLE
Download Pretrained Models Not Found

### ISSUE THREAD

**Issue by Ahmed0Sultan** [Hironsan/anago#76]
I'm trying to download a pretrained model as described in the docs, but other than the English model, it gives me the following 
`Anonymous caller does not have storage.objects.get access to chakki/datasets/public/ner/model_ar.zip.`

**Comment by Hironsan** [comment]
Hello @Ahmed0Sultan 

I published the Arabic pre-trained model as follows:

* [https://storage.googleapis.com/chakki/datasets/public/ner/model_ar.zip](https://storage.googleapis.com/chakki/datasets/public/ner/model_ar.zip)
