### ISSUE TITLE
Seems example code is outdated

### ISSUE THREAD

**Issue by aviezab** [Hironsan/anago#84]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Manjaro Linux update Sept 6, 2018
- **TensorFlow/Keras version**: 1.8.0, 2.2.2
- **Python version**: 3.6.5

### Describe the problem
![image](https://user-images.githubusercontent.com/34294278/45134733-3ffd3580-b1c6-11e8-9093-c57005e55478.png)

I check the BiLSTMCRF class, I found no load function there.

### Source

'''
Tagging example
'''
import argparse
import os
from pprint import pprint

from anago.tagger import Tagger
from anago.models import BiLSTMCRF
from anago.preprocessing import IndexTransformer

def main(args):
    print("Loading objects...")
    model = BiLSTMCRF.load_model(args.weights_file, args.params_file)
    it = IndexTransformer.load(args.preprocessor_file)
    tagger = Tagger(model, preprocessor=it)

    print("Tagging a sentence...")
    res = tagger.analyze(args.sent)
    pprint(res)

if __name__ == '__main__':
    SAVE_DIR = os.path.join(os.path.dirname(__file__), './mymodel')
    parser = argparse.ArgumentParser(description='Tagging a sentence.')
    parser.add_argument('--sent', default='Jokowi Kumpulkan Wali Kota Seluruh Indonesia, Airin Hadir')
    parser.add_argument('--save_dir', default=SAVE_DIR)
    parser.add_argument('--weights_file', default=os.path.join(SAVE_DIR, 'model_weights.h5'))
    parser.add_argument('--params_file', default=os.path.join(SAVE_DIR, 'params.json'))
    parser.add_argument('--preprocessor_file', default=os.path.join(SAVE_DIR, 'preprocessor.json'))
    args = parser.parse_args()
main(args)

**Comment by eshijia** [comment]
The problem still exists. What is the correct pipeline for using anago? The provided examples (training and tagger) seem to be out of date.

**Comment by limuos** [comment]
> The problem still exists. What is the correct pipeline for using anago? The provided examples (training and tagger) seem to be out of date.

Did you find any solution?

**Comment by aviezab** [comment]
@eshijia @soumandal Do You guys still need the example code? I can provide it.

**Comment by soumandal** [comment]
> @eshijia @soumandal Do You guys still need the example code? I can provide it.

Sure, that would be great.

**Comment by aviezab** [comment]
> > @eshijia @soumandal Do You guys still need the example code? I can provide it.
> 
> Sure, that would be great.

Here You go
https://gist.github.com/aviezab/78e0db5f33da666c33eb70586eb36c72
