### ISSUE TITLE
Demo not working

### ISSUE THREAD

**Issue by siberio76** [Hironsan/anago#86]
It seems that the demo site is down or broken. Please can you check what happened?

Thanks a lot

**Comment by Hironsan** [comment]
OK, I'll check it.

But it maybe takes a few days to solve the problem.

Thanks.

**Comment by Hironsan** [comment]
Solved!

**Comment by siberio76** [comment]
Tnx Hiroki... I’ll try right now.

Have a good day!

Il giorno mar 18 set 2018 alle 08:58 Hiroki Nakayama <
notifications@github.com> ha scritto:

**Comment by siberio76** [comment]
Hi Hiroki,
one more thing... Is there a paper from you that I can cite as reference
(in addition to Lample, Guillaume, et al., NAACL 2016)?

Let me know,
Stefano

2018-09-18 9:34 GMT+02:00 stefano silvestri <stefano.silvestri@icar.cnr.it>:
