### ISSUE TITLE
tag different result from same input sentence

### ISSUE THREAD

**Issue by michaelwangtd** [Hironsan/anago#9]
hi，@Hironsan . I have trained a model named 'model_weight.h5' .
Then loaded model to tag:tagger = anago.Tagger(model_config, weights, save_path=SAVE_ROOT, preprocessor=p)
but when I use same sentence return different result,I am puzzling.
Please giving same suggestion.
input:<class 'str'> President Obama is speaking at the White House.
output:
[('President', 'O'), ('Obama', 'O'), ('is', 'PER'), ('speaking', 'PER'), ('at', 'O'), ('the', 'O'), ('White', 'O'), ('House.', 'LOC')]
[('President', 'O'), ('Obama', 'O'), ('is', 'O'), ('speaking', 'MISC'), ('at', 'MISC'), ('the', 'O'), ('White', 'LOC'), ('House.', 'LOC')]
[('President', 'O'), ('Obama', 'O'), ('is', 'O'), ('speaking', 'O'), ('at', 'O'), ('the', 'O'), ('White', 'O'), ('House.', 'O')]

**Comment by Hironsan** [comment]
In anago 1.0.0, this problem is probably solved.
Thanks!

```python
>>> text = 'President Obama is speaking at the White House.'
>>> model = anago.Sequence.load('weights.h5', 'params.json', 'preprocessor.pickle')
>>> model.analyze(text)
{'words': ['President', 'Obama', 'is', 'speaking', 'at', 'the', 'White', 'House.'], 'entities': [{'text': 'Obama', 'type': 'PER', 'score': 1.0, 'beginOffset': 1, 'endOffset': 2}, {'text': 'White House.', 'type': 'LOC', 'score': 1.0, 'beginOffset': 6, 'endOffset': 8}]}
>>> model.analyze(text)
{'words': ['President', 'Obama', 'is', 'speaking', 'at', 'the', 'White', 'House.'], 'entities': [{'text': 'Obama', 'type': 'PER', 'score': 1.0, 'beginOffset': 1, 'endOffset': 2}, {'text': 'White House.', 'type': 'LOC', 'score': 1.0, 'beginOffset': 6, 'endOffset': 8}]}
>>> model.analyze(text)
{'words': ['President', 'Obama', 'is', 'speaking', 'at', 'the', 'White', 'House.'], 'entities': [{'text': 'Obama', 'type': 'PER', 'score': 1.0, 'beginOffset': 1, 'endOffset': 2}, {'text': 'White House.', 'type': 'LOC', 'score': 1.0, 'beginOffset': 6, 'endOffset': 8}]}
```
